# Generated by Django 4.2.4 on 2024-06-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo', models.TextField(choices=[('RECLAMO', 'reclamo'), ('FELICITACIONES', 'Felicitaciones')])),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('evidencia', models.ImageField(upload_to='', verbose_name='Evidencia')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'db_table': 'form',
            },
        ),
    ]
